### PR TITLE
Update to charmcraft 3

### PR DESCRIPTION
**Pull request by samuelallan72**
Fixes: #95

### CODE REVIEW

**Review by chanchiwai-ray — APPROVED** [review]
LGTM, side question: do we need to update `charmcraft.yaml`?

**Comment by samuelallan72** [comment]
> do we need to update charmcraft.yaml?

I believe not - it builds fine. :)

**Review by aieri — APPROVED** [review]

**Comment by gabrielcocenza** [comment]
> LGTM, side question: do we need to update charmcraft.yaml?

I thought the same....

I imagine that it's not every project that will work

**Comment by samuelallan72** [comment]
> I imagine that it's not every project that will work

Yes, some projects will not work, but most should be fine. We originally pinned everything to charmcraft 2 even if it seemed to work, because of some bugs in earlier releases of charmcraft 3 around handling of bases.

**Pull request merged**
